cat_bot_geo_loc:
    resource: "@CatBotGeoLocBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

map:
  resource: '@CatBotGeoLocBundle/Controller/'
  type: annotation

test:
  resource: '@CatBotGeoLocBundle/Controller/'
  type: annotation

post:
  resource: '@CatBotGeoLocBundle/Controller/'
  type: annotation
  methods: POST